FROM python:3.12-slim
LABEL maintainer=daweizhou

RUN apt-get update && apt-get install -y --no-install-recommends
 
WORKDIR /

COPY backup.py /backup.py

ENV backup_name=backup
ENV backup_type=xztar

VOLUME [ "/data","/destination" ]

CMD python3 /backup.py /data /destination $backup_type $backup_name 
