FROM python:3.12-slim
LABEL maintainer=daweizhou

WORKDIR /

COPY backup.py /backup.py

ENV backup_name=backup
ENV backup_type=xztar

VOLUME [ "/data" ]
VOLUME [ "/destination"]

CMD python3 /backup.py /data /destination $backup_type $backup_name 
