services:
  proxy:
    image: nginx:stable-alpine
    container_name: proxy-server
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./certs:/etc/nginx/certs:ro"
    command: ["nginx","-g","daemon off;"]
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - "fileserver"
    restart: always

  fileserver:
    image: filebrowser/filebrowser
    container_name: fileserver
    volumes:
      - ./files/data:/srv
      - ./files/database:/database
      - ./files/config:/config
    expose:
      - "80"
    restart: always

