version: "3"

services:
  minecraft:
    image: itzg/minecraft-server:latest
    ports:
      - "25555:25565"
    volumes:
      - ../worlds_backup:/data
    environment:
      MEMORY: "6G"
      EULA: "TRUE"
      TYPE: "PAPER"
      OVERRIDE_SERVER_PROPERTIES: "TRUE"
      SERVER_NAME: "DAYAISANANIMAL"
      MAX_PLAYERS: "20"
      ONLINE_MODE: "TRUE"
      ENABLE_COMMAND_BLOCK: "TRUE"
      MODE: "SURVIVAL"
      DIFFICULTY: "NORMAL"
      SPAWN_PROTECTION: "0"
      ALLOW_FLIGHT: "TRUE"
      MOTD: |
        A %TYPE% server on %VERSION%
        Daya è un animale
    tty: true
    stdin_open: true
    restart: always
