
services:
  minecraft:
    image: itzg/minecraft-server:latest
    ports:
      - "25555:25565"
    volumes:
      - ./world:/data/world
    environment:
      MEMORY: "6G"
      EULA: "TRUE"
      TYPE: "PAPER"
      OVERRIDE_SERVER_PROPERTIES: "TRUE"
      SERVER_NAME: "PAPERINO"
      MAX_PLAYERS: "20"
      ONLINE_MODE: "TRUE"
      ENABLE_COMMAND_BLOCK: "TRUE"
      MODE: "SURVIVAL"
      DIFFICULTY: "NORMAL"
      SPAWN_PROTECTION: "0"
      ALLOW_FLIGHT: "TRUE"
      MOTD: |
        A %TYPE% server on %VERSION%
    tty: true
    stdin_open: true
    restart: always
  mod_minecraft:
    image:  itzg/minecraft-server:latest
    ports:
      - "25565:25565"
    volumes:
      - ./mod_world:/data
      - ./mods:/data/mods:rw
    environment:
      MEMORY: "10G"
      EULA: "TRUE"
      TYPE: "FORGE"
      FORGE_VERSION: "47.4.3"
      VERSION: "1.20.1"
      OVERRIDE_SERVER_PROPERTIES: "TRUE"
      SERVER_NAME: "BUDINI"
      VIEW_DISTANCE: "6"
      MAX_PLAYERS: "10"
      ONLINE_MODE: "TRUE"
      ENABLE_COMMAND_BLOCK: "TRUE"
      MODE: "SURVIVAL"
      DIFFICULTY: "NORMAL"
      SPAWN_PROTECTION: "0"
      ALLOW_FLIGHT: "TRUE"
      MOTD: |
        A %TYPE% server on %VERSION%
        Budini Mod Server GG!!!
    tty: true
    stdin_open: true
    restart: always

    
